[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1hbhwKq2vEju3KSpkRwF6FsBQ3VMF_iGh2V2pvjo39hI/edit?usp=sharing"
type = "service_account"
project_id = "calm-buttress-484908-e7"
private_key_id = "f74b5793b0fa8116dc9977c623367ee930e48dee"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkpAjo2+K8SZSx
P+kSqi41cTb0S9n8oLKOcOlRGMdGSBGuL3IUGBZTP2oinQkX2Pj8x4sOC/ZYJKRI
xsiJerjqdUI7m1WAG4I6B8OLNUBjX1UWKwjF5qxfRkCQKEnyn7P86CzxEv5hnPAn
SD4uHt0njBYGcM8BAwdwTShy/rQAw/5yUdxR8bcvhTM0OGyABg8GdFwM1bhTPLSX
vud9w1ZnxAfjVM/iq/JIDq1YgzD24697SmbNXqUDC0qvvuV4lpUiIzJ9k/zom3hZ
Ris4opHtpBIRWLix91r9VxPiCAt8MqqecYqiBCBYAWxpq1+nXwwC3aqX7LHy/IrO
XzRsdjTbAgMBAAECggEAHL3qNESWu4oY5CylErYU5Q2Dq3hGcNzY7xb1FExAFZvl
QkRUJP/jfdr3O12wxbICHZb0Rpp+Afs7ltzlC2MaPwwDaQaAEaI7xMewMnA0cmSl
JP6URIA1nVhVUxVFe463zDH4DonjUMUmA6WP/Vsz/oBtI+izqpiNxuQhaJngcLV+
dDsUCuP5Bga75lTd2zQ9c0qqlm1MW4qmPuLyMNUm8EMUtvsHVJzpE5ctM1+7Qo5z
APZRar8nVJ+7qnxxaZ3n4W0ba8tzdj+WsguJr1AIQ7bqH8vpeLhuwStx0+E/oiG+
IZjDpEbYECJNaBeMMMhWPHg5P1t8j66wYiXEWXjCSQKBgQDkLzV7R0o0/lS1yhfc
VgOVg2LhQERTR4ds7iQecwZMkzt2xNY0cSuv/u3p3DqwcCge3/wviWHKEfq2arlU
zlpkTTfI/3XPrFW/ezVX3aDY3vGRaSwMXYVFn1toGLzJlpXFKfG77J+7iXmIu+4P
GwWI62qif/SxAOSU8aUQqXORTQKBgQC4td0d8AygSZWVtouaqB3kgCJrtz8aEYaQ
dgCGl1bmCtD/VxxZQ6Ag+r2IPqmCPicLh4SrdgHGslgnBtZazi+JkPFM4FmUDvAo
qhqtTD7AM28iDx/HXi5i7hmtRzj3CrQMmtp9nkRpTgTpmXIgRstWMB6R3rcjcfcF
nkuuqiBKxwKBgQCSjQtxSMENNgdb1hbrCUc2AHNCLg9z2S3ONUh3UfLKvYjkZ9kX
R1QCrd1JZItBBFeQNNT4BukKae+2tuae5AVEBB/+9KtKnOlZmJ0S+KG0h8NoW77R
lkLhC08elTyy0AcS4TSDOJ8CSHII8oIbq4Qrgt8yzLFv+R3V1zjncZ1qxQKBgEI7
lEpD5YMkX6sLhguy9OUWvUD6uHnUhvgOGCoq4lIi1sZ4qgWoJictQgE01vuI5d9Q
fNYuvnxNPybfYMW24XzmqF/0oqpgoOUz+dTiXi31Q4hm+/I1Z1S6JCLqQxbyk5Vh
ga9BrS5Fd6V8DFxehlMldhDAV9Mx7m3pUSIUhvfJAoGAfT13UdNmg8AlyGQd6CbC
4arzMYz7RtV7IexKo4f5YuZrfv2SCdiYb7+78yld03iq/yK4ip9xuMDdBsW8YTZ4
QVl+kC2367qroCMaTYx2/Of5bIsL4suO8HgKbZ67IN71ZWLMz3ueX9cd4tZwmHd4
5QI7z9FMN5z2td+WEHEyWtY=
-----END PRIVATE KEY-----"""
client_email = "mr-scheduling@calm-buttress-484908-e7.iam.gserviceaccount.com"
client_id = "118024086876997871322"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mr-scheduling%40calm-buttress-484908-e7.iam.gserviceaccount.com"